name: Deploy KOGE

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    uses: 2BAB/minibook-kit/.github/workflows/deploy-github-pages.yml@v0.1.2
    with:
      book: koge
