name: Deploy KOGE

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: 2BAB/minibook-kit/.github/workflows/deploy-github-pages.yml@v0.1.4
    with:
      book: koge
